### ISSUE TITLE
archive of old GO.db releases

### ISSUE THREAD

**Issue by boegel** [Bioconductor/GO.db#1]
Is there an archive of old GO.db releases available somewhere?

GO.db 3.11.1 used to be part of Bioconductor 3.11, but was later bumped to 3.11.4, and now we can't seem to find the sources for GO.db 3.11.1 anymore...

For most Bioconductor packages, there is an archive available at https://bioconductor.org/packages/3.11/bioc/src/contrib/Archive/, but GO.db isn't in there...

**Comment by hpages** [comment]
Hi,

We archive software packages only. No archive for data packages, sorry.

GO.db 3.11.1 was containing a very outdated snapshot of GO and really really needed an update. The update was scheduled for the BioC 3.11 release but came in a little bit later. See https://support.bioconductor.org/p/131482/ 

Note that it's important to keep other annotation packages (e.g. the `org.*.db` packages) closely synchronized with GO.db so downgrading from GO.db 3.11.4 to 3.11.1 without also downgrading the `org.*.db` packages would be like opening a can of worms.

Best,
H.

**Comment by boegel** [comment]
Thank you for the quick reply and warning about keeping GO.db in sync with the other `*.db` packages.

Is there a specific reason not to archive data packages? Limited disk capacity?

Making source tarballs disappear for packages that were previously part of a Bioconductor release is really annoying, and basically makes reproducing installations impossible.

In fact, even in-place updates in a Bioconductor release sort of render releases meaningless. What's the point of tagging releases if what is included in the releases changes over time?!

**Comment by lshep** [comment]
An archive of past releases ie. the last version of GO.db for Bioc 3.10 (or other bioconductor versions) is available but as @hpages it is recommended to keep everything in sync and use the most recent versions of  R/Bioc/packages.

**Comment by mtmorgan** [comment]
It seems the issue about availability of 3.11.1 has been resolved so I'll close the issue.

Broader discussion about archive policy would be better discussed on, e.g., the [bioc-devel][1] forum. If the discussion were moved there, I might say that I would not be opposed to adopting the same archive policy for annotation & experiment data packages as for software packages. Because science moves quickly and six months is a long time for a buggy package, I would be opposed to a strict release; maybe there is a monthly patch release concept that could be applied. If strict reproducibility in the face of an unsatisfactory release policy is a priority then that is an [rsync command][2] away.

[1]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[2]: http://bioconductor.org/about/mirrors/mirror-how-to/

**Comment by boegel** [comment]
@mtmorgan Well, the availability of GO.db 3.11.1 is not really resolved, since it's no longer available...
But there maybe little to do about it at this point, I guess.

W.r.t. setting up a mirror: Bioconductor is one of the almost 2000 (bundles of) software packages that we support in EasyBuild (see https://easybuild.readthedocs.io/en/latest/version-specific/Supported_software.html), yet the issue of disappearing sources tarballs only occurs with a handful of those, Bioconductor being one of them.

Setting up and maintaining a mirror or an archive ourselves for everything we support just in case stuff disappears (or worse, is changed without a version bump) is an additional complication we would rather not have to deal with. But maybe we'll have to it seems...

**Comment by mtmorgan** [comment]
it's resolved, just not the way you want it to be!

Please take other discussion to a more appropriate forum.
